### ISSUE TITLE
IOS - Deadlock when location permission is denied

### ISSUE THREAD

**Issue by fsaffioti** [jamesmontemagno/GeolocatorPlugin#129]
There is a deadlock when LocationStartAsync is called and in the meanwhile the user didn't give permission to use Location Service

Steps to reproduce
1)uninstalling/reinstalling the app
2)launch the app that calls LocationStartAsync
3)When location permission popup appear click Deny
4)Deadlock without throwing an error

**Comment by prashantvc** [comment]
@fsaffioti 
Could you fill out following information? It will help us to troubleshoot the issue

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior

### Expected Behavior

### Actual Behavior

### Code snippet

### Screenshotst

**Comment by fsaffioti** [comment]
Version Number of Plugin: 4.0.1
Device Tested On: Iphone 5s
Simulator Tested On: Iphone 7 iOS 10
Version of VS: 7.1.5
Mono: 5.2.0.224 

Currently I fixed this bug checking CLLocationManager.Status with a my function. If Permission status is CLAuthorizationStatus.NotDetermined, Geolocator.StartListeningAsync is not called

**Comment by jamesmontemagno** [comment]
Yeah, it will request the permission and then throw an exception if you don't have access.

var hasPermission = await CheckPermissions();
			if (!hasPermission)
				throw new GeolocationException(GeolocationError.Unauthorized);

This code looks correct to me.

**Comment by prashantvc** [comment]
Marking this issue closed based on ^ comments
