### ISSUE TITLE
UWP IsGeoLocationEnabled returns true even when location is disabled

### ISSUE THREAD

**Issue by cmeeren** [jamesmontemagno/GeolocatorPlugin#144]
Note: This bug also affects the CrossPermissions plugin.

## Bug Information

Version Number of Plugin: 4.0.1
Simulator Tested On: Visual Studio Emulator
Version of VS: 15.3
Version of Xamarin: 4.6.0.299 (Android SDK: 7.4.0.21)

### Steps to reproduce the Behavior

In an UWP app:

1. Request location permission. Grant it in the app when prompted.
2. Disable location in the device settings.
3. Check the permission. It is `Denied`; it should be `Granted`.
4. Request permission. It will automatically return `Granted` without any prompt to the user.
5. Check `CrossGeolocator.Current.IsGeolocationEnabled`. It returns `true`; it should return `false` since locationing is disabled.

**Comment by jamesmontemagno** [comment]
IsGeolocationEnabled only checks to see if it is disabled and available.

via:  https://docs.microsoft.com/en-us/uwp/api/windows.devices.geolocation.positionstatus

Disabled | Location settings are turned off. This status indicates that the user has not granted the application permission to access location.

NotAvailable | Location services is not available on this version of Windows.


To check permission RequestAccessAsync always has to be called like the permission plugin does: https://github.com/jamesmontemagno/PermissionsPlugin/blob/master/src/Plugin.Permissions.UWP/PermissionsImplementation.cs#L88

This is most likely why the permission is coming back denied, which makes sense if that is what UWP is telling me. The permissions plugin for UWP does not implement the request and always returned granted . 



Implementation here is correct though.

**Comment by jamesmontemagno** [comment]
Specifically now reading this: https://docs.microsoft.com/en-us/uwp/api/windows.devices.geolocation.geolocator#Windows_Devices_Geolocation_Geolocator_RequestAccessAsync

There is no way to find out this information unless you are actively tracking it. Assumption here is that perhaps every single Windows device has geolocator capabilities....

he LocationStatus property is updated dynamically only when a tracking session is active. Otherwise, it is either NotInitialized or Disabled.

Seeing this it does look like it should return disabled if it is disabled.
