### ISSUE TITLE
GeolocatorSample.iOS doesn't work in iOS11

### ISSUE THREAD

**Issue by alexreich** [jamesmontemagno/GeolocatorPlugin#169]
## Bug Information

Version Number of Plugin: from latest Source
Device Tested On: iPhone 8 iOS 11.0
Simulator Tested On: Mac Mini
Version of VS: 2017 (15.4.0)
Version of Xamarin: 4.7.10.22 (iOS / Mac 11.2.0.8)
Versions of other things you are using:

### Steps to reproduce the Behavior
Launch app in iOS 11
Go to Home / Settings
Go into GeolocatorSample
### Expected Behavior
App challenges to allow location updates
Shows "ALLOW GEOLOCATORSAMPLE TO ACCESS" with Location setting
![2017-10-16_11-31-44-am](https://user-images.githubusercontent.com/9328531/31628484-aa8009a2-b265-11e7-8efb-c0eee5758da8.jpg)
### Actual Behavior
Missing Location entry from settings

### Screenshots
![2017-10-16_11-31-57-am](https://user-images.githubusercontent.com/9328531/31628485-aa985cdc-b265-11e7-8d59-e0847edaa4ca.jpg)

**Comment by PureWeen** [comment]
I'm having the same issue

I found this SO post about the new permission in iOS 11
https://stackoverflow.com/questions/44424092/location-services-not-working-in-ios-11

The solution is to
```
Good news, if you follow the advice of the debugging console, IE. add both the new key NSLocationAlwaysAndWhenInUseUsageDescription and one of the old keys NSLocationWhenInUseUsageDescription, locations services will start to work again.
```

But when I added that permission then I start getting the following exception 

```
{System.Exception: StartListeningForPositionChanges ---> System.UnauthorizedAccessException: On iOS 8.0 and higher you must set either NSLocationWhenInUseUsageDescription or NSLocationAlwaysUsageDescription in your Info.plist file to enable Authorization Requests for Location updates!
  at Plugin.Permissions.PermissionsImplementation.RequestLocationPermission (Plugin.Permissions.Abstractions.Permission permission) [0x00125] in <4d7e39460bb6469e800e7b3001922097>:0 
  at Plugin.Permissions.PermissionsImplementation+<RequestPermissionsAsync>d__8.MoveNext () [0x002dd] in <4d7e39460bb6469e800e7b3001922097>:0 
```

**Comment by PureWeen** [comment]
To clarify I just get this exception
```
System.UnauthorizedAccessException: On iOS 8.0 and higher you must set either NSLocationWhenInUseUsageDescription or NSLocationAlwaysUsageDescription in your Info.plist file to enable Authorization Requests for Location updates!
```
Only when I upgrade to the latest version. I don't have this issue with 4.0.1


I think the problem is that StartListeningAsync requests LocationAlways for the permission

But the if statement here
https://github.com/jamesmontemagno/PermissionsPlugin/commit/415df0fed52bf9c7bcc6cf1cb218b9b5bd3ec4a8#diff-213a971bb119c1a26d78fd32d2eb2a47R292

Assumes you need the "NSLocationAlwaysUsageDescription " set to "Listen" but I don't think that's true

You can still "listen" for position changes when all you have set is this "NSLocationWhenInUseUsageDescription "

And the user still has the app running. The only way I know to get that blue bar to show up that indicates you are being track is to use the "NSLocationWhenInUseUsageDescription " permission instead of the "NSLocationAlwaysUsageDescription " permission

**Comment by jamesmontemagno** [comment]
Fixed, just send a PR next time
