### ISSUE TITLE
Heading inconsistent between platforms

### ISSUE THREAD

**Issue by baverbud** [jamesmontemagno/GeolocatorPlugin#19]
On Android, Location.Bearing is used which according to the documentation (https://developer.android.com/reference/android/location/Location.html#getBearing()):

> Bearing is the horizontal direction of travel of this device, and is not related to the device orientation. It is guaranteed to be in the range (0.0, 360.0] if the device has a bearing. 

But on iOS GeolocatorImplementation uses CLLocationManager's heading, which according to https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/GettingHeadings/GettingHeadings.html:

> Devices with a magnetometer can report the direction in which a device is pointing, also known as its heading. 

Instead of using CLLocation's Course which is defined as (https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocation_Class/index.html#//apple_ref/occ/instp/CLLocation/course):

> The direction in which the device is traveling. 

I'm not familiar enough with windows phone to comment on its implementation.
## Feature Request:

Unification between the platforms. Both Android and iOS provide GPS-based bearing (course) information. I expected an iOS geolocation api to provide the course bearing, not the magnetometer heading. 

Also, in the interest of compartmentalization, shouldn't the plugin prioritize the use of the GPS-based data, and provide a means (ex. HasHeading property) for developers to determine if they need to fall back on a sensor (which could be accessed via a sensor plugin)?

**Comment by fsaffioti** [comment]
Is there any update on this? when will it be integrated the CLLocation course property?

**Comment by mjorrens** [comment]
In reviewing the PlugIn code, I think the change for this should be:

In GeolocatorImplementation.apple.cs --> UpdatePostion()  --> Bolded code below

...
#if __IOS__ || __MACOS__
			**if (location.Course > -1)
				p.Heading = location.Course;**
            if (location.Speed > -1)
                p.Speed = location.Speed;
#endif
....

Lastly, I believe the IncludeHeading argument should be removed from the "GetPosition..." methods as it creates confusion as it adds in the compass heading (for iOS only).

**Comment by jixer** [comment]
@mjorrens @baverbud I know this is an old thread, but thanks for tracking this down.  

Our app is using this value as well and we were a bit caught off guard as we assumed the Heading was a reflection of course and not the direction in which a device is pointing.  I feel that modifying to utilize course is a better choice as it aligns the two platforms (Android & iOS) and seems a bit more aligned to what developers will expect when using the library.

Since it's up for grabs, I will work on a pull request as I find time.  I'll create a solution based upon iOS documentation and @mjorrens's recommendations.  Any concerns around changing this in the event some are actually using this value for the purpose of reporting the direction in which a device is pointing?  I personally feel that magnetometer based headings should be contained in its own library or function and not a part of Geolocator.  Thoughts @jamesmontemagno and team?
